// ============================================================
//  LibraryQuiet – reports-manager.js  (uses AppData)
// ============================================================

const REPORT_TYPES = [
  { type:'Daily Noise Report',       icon:'📊', desc:'Summary of today\'s noise levels per zone' },
  { type:'Weekly Summary Report',    icon:'📅', desc:'7-day noise trend and zone comparison' },
  { type:'Alert Frequency Report',   icon:'⚠️', desc:'Alert counts, types and resolution times' },
  { type:'Occupancy vs Noise Report',icon:'👥', desc:'Correlation between occupancy and noise' },
  { type:'Monthly Report',           icon:'📆', desc:'Monthly noise statistics and analysis' },
  { type:'Zone Performance Report',  icon:'▦',  desc:'Individual zone compliance and history' },
];

let currentTab   = 'all';
let pendingType  = '';
let viewTargetId = null;

function el(id)        { return document.getElementById(id); }
function setText(id,v) { const e=el(id); if(e) e.textContent=v; }

function startClock() {
  const update = () => {
    const now = new Date();
    setText('tb-date', now.toLocaleDateString('en-PH',{weekday:'long',year:'numeric',month:'long',day:'numeric'}) + ' · ' + now.toLocaleTimeString('en-PH'));
  };
  update(); setInterval(update, 1000);
}
function toggleSidebar() { el('sidebar').classList.toggle('collapsed'); }

// ── STATS ──────────────────────────────────────────────────
function renderStats() {
  const session = AppData.getSession();
  const reports = AppData.getReports().filter(r=>r.generatedBy===session?.name||r.role==='Library Manager');
  const today   = AppData.today();
  setText('s-total',   reports.length);
  setText('s-today',   reports.filter(r=>r.date===today).length);
  setText('s-sent',    reports.filter(r=>r.sentToAdmin).length);
  setText('s-pending', reports.filter(r=>!r.sentToAdmin).length);
  AppData.updateNotifBadge();
}

// ── REPORT TYPE CARDS ──────────────────────────────────────
function renderReportTypes() {
  const grid = el('report-type-grid'); if (!grid) return;
  grid.innerHTML = REPORT_TYPES.map(rt=>`
    <div class="rt-card" onclick="openGenModal('${rt.type}')">
      <div class="rt-icon">${rt.icon}</div>
      <div class="rt-name">${rt.type}</div>
      <div class="rt-desc">${rt.desc}</div>
    </div>`).join('');
}

// ── GENERATE MODAL ─────────────────────────────────────────
function openGenModal(type) {
  pendingType = type;
  el('gen-title').textContent = type;
  el('gen-type').value        = type;
  el('gen-notes').value       = '';
  el('gen-send').checked      = false;
  // Build preview
  const zones  = AppData.getZones();
  const alerts = AppData.getAlerts();
  const avg    = Math.round(zones.reduce((a,z)=>a+z.level,0)/zones.length);
  el('report-preview').innerHTML=`
    <div class="rp-title">📋 Report Preview</div>
    <div class="rp-row"><span class="rp-label">Report Type</span><span class="rp-val">${type}</span></div>
    <div class="rp-row"><span class="rp-label">Avg Noise</span><span class="rp-val">${avg} dB</span></div>
    <div class="rp-row"><span class="rp-label">Total Zones</span><span class="rp-val">${zones.length}</span></div>
    <div class="rp-row"><span class="rp-label">Active Alerts</span><span class="rp-val">${alerts.filter(a=>a.status==='active').length}</span></div>
    <div class="rp-row"><span class="rp-label">Date</span><span class="rp-val">${AppData.today()}</span></div>`;
  el('gen-overlay').classList.add('show'); el('gen-modal').classList.add('show');
}

function closeGenModal() { el('gen-overlay').classList.remove('show'); el('gen-modal').classList.remove('show'); }

async function confirmGenerate() {
  const session  = AppData.getSession();
  const notes    = el('gen-notes').value.trim();
  const sendNow  = el('gen-send').checked;
  const now      = new Date();
  const zones    = AppData.getZones();
  const alerts   = AppData.getAlerts();
  const report   = {
    id:          'R-'+Date.now(),
    type:        pendingType,
    generatedBy: session?.name||'Library Manager',
    role:        session?.role||'Library Manager',
    date:        AppData.today(),
    time:        now.toLocaleTimeString('en-PH',{hour:'2-digit',minute:'2-digit'}),
    sentToAdmin: sendNow,
    adminReadAt: null,
    notes:       notes || `Generated by ${session?.name||'Manager'} on ${AppData.today()}.`,
    data: {
      avgNoise:    Math.round(zones.reduce((a,z)=>a+z.level,0)/zones.length),
      totalZones:  zones.length,
      quietZones:  zones.filter(z=>z.level<40).length,
      loudZones:   zones.filter(z=>z.level>=60).length,
      activeAlerts:alerts.filter(a=>a.status==='active').length,
      totalAlerts: alerts.length,
    },
  };
  await AppData.addReport(report);

  if (sendNow) {
    // Notify admin via AppData notification
    AppData.addNotification({
      id:       'N-'+Date.now(),
      type:     'report',
      title:    'New Report from Manager',
      msg:      `${session?.name||'Manager'} sent: ${pendingType}`,
      from:     session?.name||'Manager',
      time:     report.time,
      date:     report.date,
      read:     false,
      reportId: report.id,
    });
    showToast(`📤 Report generated & sent to Admin!`,'success');
  } else {
    showToast(`📋 Report "${pendingType}" generated!`,'success');
  }

  closeGenModal(); renderStats(); renderTable();
}

// ── TABLE ──────────────────────────────────────────────────
function getFiltered() {
  const session = AppData.getSession();
  let reports   = AppData.getReports().filter(r=>r.generatedBy===session?.name||r.role==='Library Manager');
  if (currentTab==='sent')    reports = reports.filter(r=>r.sentToAdmin);
  if (currentTab==='notsent') reports = reports.filter(r=>!r.sentToAdmin);
  return reports;
}

function setTab(tab, btn) {
  currentTab=tab;
  document.querySelectorAll('.ftab').forEach(b=>b.classList.remove('active'));
  btn.classList.add('active'); renderTable();
}

function renderTable() {
  const tbody   = el('reports-tbody'); if (!tbody) return;
  const reports = getFiltered();
  setText('tbl-count',`Showing ${reports.length} report${reports.length!==1?'s':''}`);

  if (reports.length===0) {
    tbody.innerHTML=`<tr><td colspan="7" style="text-align:center;padding:40px;color:var(--light);">No reports yet. Generate one above!</td></tr>`;
    return;
  }

  tbody.innerHTML = reports.map((r,i)=>{
    const sentBadge = r.sentToAdmin ? '<span class="badge b-teal">📤 Sent</span>' : '<span class="badge b-gray">Not sent</span>';
    const sendBtn   = !r.sentToAdmin ? `<button class="tbl-btn tb-send" onclick="sendToAdmin('${r.id}')">📤 Send</button>` : '';
    return `<tr id="rrow-${r.id}">
      <td style="color:var(--muted);">${i+1}</td>
      <td style="font-weight:800;">${r.type}</td>
      <td style="color:var(--muted);font-size:12px;">${r.date}</td>
      <td style="color:var(--muted);font-size:12px;">${r.time}</td>
      <td>${sentBadge}</td>
      <td style="color:var(--muted);font-size:12px;max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">${r.notes||'—'}</td>
      <td>
        <div class="action-btns">
          <button class="tbl-btn tb-view" onclick="openView('${r.id}')">👁 View</button>
          ${sendBtn}
          <button class="tbl-btn tb-dl"   onclick="downloadReport('${r.id}')">⬇</button>
        </div>
      </td>
    </tr>`;
  }).join('');
}

// ── SEND TO ADMIN ──────────────────────────────────────────
async function sendToAdmin(id) {
  const session = AppData.getSession();
  await AppData.sendReportToAdmin(id, session?.name||'Library Manager');
  renderStats(); renderTable();
  showToast('📤 Report sent to Administrator!','success');
}

// ── VIEW MODAL ─────────────────────────────────────────────
function openView(id) {
  const r = AppData.getReports().find(x=>x.id===id); if (!r) return;
  viewTargetId = id;
  el('view-title').textContent = r.type;
  const sentLbl = r.sentToAdmin ? `📤 Yes — sent at ${r.sentAt||r.time}` : '— Not sent yet';
  el('view-body').innerHTML=`
    <div class="view-grid">
      <div class="view-field"><div class="vf-label">Report ID</div><div class="vf-val" style="font-family:monospace;font-size:12px;">${r.id}</div></div>
      <div class="view-field"><div class="vf-label">Generated By</div><div class="vf-val">${r.generatedBy}</div></div>
      <div class="view-field"><div class="vf-label">Date</div><div class="vf-val">${r.date}</div></div>
      <div class="view-field"><div class="vf-label">Time</div><div class="vf-val">${r.time}</div></div>
      <div class="view-field" style="grid-column:1/-1"><div class="vf-label">Sent to Admin</div><div class="vf-val">${sentLbl}</div></div>
      <div class="view-divider"></div>
      <div class="view-field" style="grid-column:1/-1"><div class="vf-label">Notes</div><div class="vf-val" style="font-weight:500;color:var(--muted);">${r.notes||'No notes.'}</div></div>
    </div>
    ${r.data?`<div class="report-data-box">
      <div class="rdb-title">Data Snapshot</div>
      <div class="rdb-row"><span class="rdb-label">Avg Noise</span><span class="rdb-val">${r.data.avgNoise} dB</span></div>
      <div class="rdb-row"><span class="rdb-label">Total Zones</span><span class="rdb-val">${r.data.totalZones}</span></div>
      <div class="rdb-row"><span class="rdb-label">Quiet / Loud</span><span class="rdb-val">${r.data.quietZones} / ${r.data.loudZones}</span></div>
      <div class="rdb-row"><span class="rdb-label">Active Alerts</span><span class="rdb-val">${r.data.activeAlerts}</span></div>
    </div>`:''}`;

  const sendBtn = el('modal-send-btn');
  if (r.sentToAdmin) { sendBtn.disabled=true; sendBtn.textContent='✓ Already Sent'; }
  else { sendBtn.disabled=false; sendBtn.textContent='📤 Send to Admin'; sendBtn.onclick=()=>{ sendToAdmin(id); closeView(); }; }

  el('view-overlay').classList.add('show'); el('view-modal').classList.add('show');
}

function downloadFromModal() { if(viewTargetId) downloadReport(viewTargetId); }
function closeView() { el('view-overlay').classList.remove('show'); el('view-modal').classList.remove('show'); }

function downloadReport(id) {
  const r = AppData.getReports().find(x=>x.id===id); if (!r) return;
  const zones  = AppData.getZones();
  const alerts = AppData.getAlerts();
  const lines  = [
    `LIBRARYQUIET – ${r.type.toUpperCase()}`,
    `${'='.repeat(50)}`,
    `Report ID   : ${r.id}`,
    `Generated By: ${r.generatedBy} (${r.role})`,
    `Date & Time : ${r.date} ${r.time}`,
    `Sent to Admin: ${r.sentToAdmin?'Yes':'No'}`,
    `Notes       : ${r.notes||'—'}`,
    ``,`ZONE SNAPSHOT`,`-`.repeat(30),
    ...zones.map(z=>`${z.name.padEnd(25)} ${Math.round(z.level)} dB`),
    ``,`ACTIVE ALERTS`,`-`.repeat(30),
    ...alerts.filter(a=>a.status==='active').map(a=>`${a.zone.padEnd(25)} ${a.level} dB — ${a.msg}`),
    ``,`Generated by LibraryQuiet System`,
  ];
  const blob=new Blob([lines.join('\n')],{type:'text/plain'});
  const url=URL.createObjectURL(blob);
  const a=document.createElement('a');
  a.href=url; a.download=`${r.type.replace(/\s+/g,'_')}_${r.date}.txt`; a.click();
  URL.revokeObjectURL(url);
  showToast('⬇ Report downloaded!','success');
}

function showToast(msg,type='info') {
  const t=el('toast'); t.textContent=msg; t.className=`toast ${type} show`;
  clearTimeout(t._t); t._t=setTimeout(()=>t.classList.remove('show'),3000);
}

document.addEventListener('keydown',e=>{ if(e.key==='Escape'){ closeView(); closeGenModal(); } });

document.addEventListener('DOMContentLoaded', async () => {
  if (window.__LQ_SESSION__) AppData._session = window.__LQ_SESSION__;
  await Promise.all([AppData.loadReports(), AppData.loadAlerts(), AppData.loadZones()]);
  AppData.applySession();
  startClock();
  renderStats();
  renderReportTypes();
  renderTable();
  AppData.updateNotifBadge();
});