// ============================================================
//  LibraryQuiet – reports-admin.js  (uses AppData)
// ============================================================

const REPORT_TYPES = [
  { type:'Daily Noise Report',       icon:'📊', desc:'Summary of today\'s noise levels per zone' },
  { type:'Weekly Summary Report',    icon:'📅', desc:'7-day noise trend and zone comparison' },
  { type:'Alert Frequency Report',   icon:'⚠️', desc:'Alert counts, types and resolution times' },
  { type:'Occupancy vs Noise Report',icon:'👥', desc:'Correlation between occupancy and noise' },
  { type:'Monthly Report',           icon:'📆', desc:'Monthly noise statistics and analysis' },
  { type:'Zone Performance Report',  icon:'▦',  desc:'Individual zone compliance and history' },
];

let currentTab    = 'all';
let viewTargetId  = null;

function el(id)        { return document.getElementById(id); }
function setText(id,v) { const e=el(id); if(e) e.textContent=v; }

function startClock() {
  const update = () => {
    const now = new Date();
    setText('tb-date', now.toLocaleDateString('en-PH',{weekday:'long',year:'numeric',month:'long',day:'numeric'}) + ' · ' + now.toLocaleTimeString('en-PH'));
  };
  update(); setInterval(update, 1000);
}
function toggleSidebar() { el('sidebar').classList.toggle('collapsed'); }

// ── STAT CARDS ─────────────────────────────────────────────
function renderStats() {
  const reports = AppData.getReports();
  const today   = AppData.today();
  const unread  = AppData.getUnreadReports();
  setText('s-total',  reports.length);
  setText('s-today',  reports.filter(r=>r.date===today).length);
  setText('s-sent',   reports.filter(r=>r.sentToAdmin).length);
  setText('s-unread', unread.length);
  // Unread banner
  const banner = el('unread-banner');
  if (unread.length>0) {
    banner.style.display='flex';
    setText('unread-title', `📋 ${unread.length} unread report${unread.length>1?'s':''} from Library Manager`);
  } else {
    banner.style.display='none';
  }
  AppData.updateNotifBadge();
}

function markAllRead() {
  AppData.getUnreadReports().forEach(async r=> await AppData.markReportRead(r.id));
  renderStats(); renderTable();
  showToast('✅ All reports marked as read.','success');
}

let pendingType = '';

// ── REPORT TYPE CARDS ──────────────────────────────────────
function renderReportTypes() {
  const grid = el('report-type-grid'); if (!grid) return;
  grid.innerHTML = REPORT_TYPES.map(rt=>`
    <div class="rt-card" onclick="openGenModal('${rt.type}')">
      <div class="rt-icon">${rt.icon}</div>
      <div class="rt-name">${rt.type}</div>
      <div class="rt-desc">${rt.desc}</div>
    </div>`).join('');
}

// ── GENERATE MODAL ─────────────────────────────────────────
function openGenModal(type) {
  pendingType = type;
  el('gen-title').textContent = type;
  el('gen-type').value        = type;
  el('gen-notes').value       = '';
  // Live data preview
  const zones  = AppData.getZones();
  const alerts = AppData.getAlerts();
  const avg    = zones.length ? Math.round(zones.reduce((a,z)=>a+z.level,0)/zones.length) : 0;
  el('report-preview').innerHTML=`
    <div class="rp-title">📊 Live Data Snapshot</div>
    <div class="rp-row"><span class="rp-label">Report Type</span><span class="rp-val">${type}</span></div>
    <div class="rp-row"><span class="rp-label">Avg Noise Level</span><span class="rp-val">${avg} dB</span></div>
    <div class="rp-row"><span class="rp-label">Total Zones</span><span class="rp-val">${zones.length}</span></div>
    <div class="rp-row"><span class="rp-label">Active Alerts</span><span class="rp-val">${alerts.filter(a=>a.status==='active').length}</span></div>
    <div class="rp-row"><span class="rp-label">Date</span><span class="rp-val">${AppData.today()}</span></div>`;
  el('gen-overlay').classList.add('show'); el('gen-modal').classList.add('show');
}

function closeGenModal() {
  el('gen-overlay').classList.remove('show'); el('gen-modal').classList.remove('show');
}

async function confirmGenerate() {
  const session = AppData.getSession();
  const notes   = el('gen-notes').value.trim();
  const now     = new Date();
  const zones   = AppData.getZones();
  const alerts  = AppData.getAlerts();
  const report  = {
    id:           'R-'+Date.now(),
    type:         pendingType,
    generatedBy:  session?.name||'Administrator',
    role:         session?.role||'Administrator',
    date:         AppData.today(),
    time:         now.toLocaleTimeString('en-PH',{hour:'2-digit',minute:'2-digit'}),
    sentToAdmin:  false,
    adminReadAt:  AppData.today(),
    notes:        notes || `Generated by ${session?.name||'Admin'} on ${AppData.today()}.`,
    data: {
      avgNoise:    zones.length ? Math.round(zones.reduce((a,z)=>a+z.level,0)/zones.length) : 0,
      totalZones:  zones.length,
      quietZones:  zones.filter(z=>z.level<40).length,
      loudZones:   zones.filter(z=>z.level>=60).length,
      activeAlerts:alerts.filter(a=>a.status==='active').length,
      totalAlerts: alerts.length,
    },
  };
  await AppData.addReport(report);
  closeGenModal();
  renderStats(); renderTable();
  showToast(`📋 "${pendingType}" generated!`, 'success');
}

// ── FILTER / TABLE ─────────────────────────────────────────
function getFiltered() {
  const reports = AppData.getReports();
  if (currentTab==='mine')     return reports.filter(r=>r.role==='Administrator');
  if (currentTab==='received') return reports.filter(r=>r.sentToAdmin&&r.role!=='Administrator');
  if (currentTab==='unread')   return reports.filter(r=>r.sentToAdmin&&!r.adminReadAt);
  return reports;
}

function setTab(tab, btn) {
  currentTab=tab;
  document.querySelectorAll('.ftab').forEach(b=>b.classList.remove('active'));
  btn.classList.add('active'); renderTable();
}

function renderTable() {
  const tbody   = el('reports-tbody'); if (!tbody) return;
  const reports = getFiltered();
  setText('tbl-count',`Showing ${reports.length} report${reports.length!==1?'s':''}`);

  if (reports.length===0) {
    tbody.innerHTML=`<tr><td colspan="8" style="text-align:center;padding:40px;color:var(--light);">No reports found.</td></tr>`;
    return;
  }

  tbody.innerHTML = reports.map((r,i)=>{
    const isUnread  = r.sentToAdmin && !r.adminReadAt;
    const sentBadge = r.sentToAdmin ? '<span class="badge b-blue">📤 Sent</span>' : '<span class="badge b-gray">—</span>';
    const rowCls    = isUnread ? 'unread-row' : '';
    return `<tr class="${rowCls}" id="rrow-${r.id}">
      <td style="color:var(--muted);">${isUnread?'🔵 ':''}${i+1}</td>
      <td style="font-weight:800;">${r.type}</td>
      <td>
        <div style="font-weight:700;">${r.generatedBy}</div>
        <div style="font-size:11px;color:var(--light);">${r.role}</div>
      </td>
      <td style="color:var(--muted);font-size:12px;">${r.date}</td>
      <td style="color:var(--muted);font-size:12px;">${r.time}</td>
      <td>${sentBadge}</td>
      <td style="color:var(--muted);font-size:12px;max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">${r.notes||'—'}</td>
      <td>
        <div class="action-btns">
          <button class="tbl-btn tb-view" onclick="openView('${r.id}')">👁 View</button>
          <button class="tbl-btn tb-dl"   onclick="downloadReport('${r.id}')">⬇ Download</button>
          <button class="tbl-btn tb-del"  onclick="deleteReport('${r.id}')">🗑</button>
        </div>
      </td>
    </tr>`;
  }).join('');
}

function deleteReport(id) {
  AppData.saveReports(AppData.getReports().filter(r=>r.id!==id));
  renderStats(); renderTable();
  showToast('🗑️ Report deleted.','info');
}

// ── VIEW MODAL ─────────────────────────────────────────────
async function openView(id) {
  const r = AppData.getReports().find(x=>x.id===id); if (!r) return;
  viewTargetId = id;
  // Mark as read
  if (r.sentToAdmin && !r.adminReadAt) { await AppData.markReportRead(id); renderStats(); renderTable(); }
  el('view-title').textContent = r.type;
  const sentBadge = r.sentToAdmin ? '📤 Yes — sent by Manager' : '— Not sent';
  el('view-body').innerHTML=`
    <div class="view-grid">
      <div class="view-field"><div class="vf-label">Report ID</div><div class="vf-val" style="font-family:monospace;font-size:12px;">${r.id}</div></div>
      <div class="view-field"><div class="vf-label">Generated By</div><div class="vf-val">${r.generatedBy}</div></div>
      <div class="view-field"><div class="vf-label">Role</div><div class="vf-val">${r.role}</div></div>
      <div class="view-field"><div class="vf-label">Date & Time</div><div class="vf-val">${r.date} · ${r.time}</div></div>
      <div class="view-field" style="grid-column:1/-1"><div class="vf-label">Sent to Admin</div><div class="vf-val">${sentBadge}</div></div>
      <div class="view-divider"></div>
      <div class="view-field" style="grid-column:1/-1"><div class="vf-label">Notes</div><div class="vf-val" style="font-weight:500;color:var(--muted);">${r.notes||'No notes provided.'}</div></div>
    </div>
    ${r.data?`<div class="report-data-box">
      <div class="rdb-title">Report Data Snapshot</div>
      <div class="rdb-row"><span class="rdb-label">Avg Noise Level</span><span class="rdb-val">${r.data.avgNoise} dB</span></div>
      <div class="rdb-row"><span class="rdb-label">Total Zones</span><span class="rdb-val">${r.data.totalZones}</span></div>
      <div class="rdb-row"><span class="rdb-label">Quiet Zones</span><span class="rdb-val">${r.data.quietZones}</span></div>
      <div class="rdb-row"><span class="rdb-label">Loud Zones</span><span class="rdb-val">${r.data.loudZones}</span></div>
      <div class="rdb-row"><span class="rdb-label">Active Alerts</span><span class="rdb-val">${r.data.activeAlerts}</span></div>
      <div class="rdb-row"><span class="rdb-label">Total Alerts</span><span class="rdb-val">${r.data.totalAlerts}</span></div>
    </div>`:''}`;
  el('view-overlay').classList.add('show'); el('view-modal').classList.add('show');
}

function downloadFromModal() { if(viewTargetId) downloadReport(viewTargetId); }
function closeView() { el('view-overlay').classList.remove('show'); el('view-modal').classList.remove('show'); }

function downloadReport(id) {
  const r = AppData.getReports().find(x=>x.id===id); if (!r) return;
  const zones  = AppData.getZones();
  const alerts = AppData.getAlerts();
  const lines  = [
    `LIBRARYQUIET – ${r.type.toUpperCase()}`,
    `${'='.repeat(50)}`,
    `Report ID   : ${r.id}`,
    `Generated By: ${r.generatedBy} (${r.role})`,
    `Date & Time : ${r.date} ${r.time}`,
    `Notes       : ${r.notes||'—'}`,
    ``,
    `ZONE SNAPSHOT`,
    `-`.repeat(30),
    ...zones.map(z=>`${z.name.padEnd(25)} ${Math.round(z.level)} dB  [${z.status}]`),
    ``,
    `ACTIVE ALERTS`,
    `-`.repeat(30),
    ...alerts.filter(a=>a.status==='active').map(a=>`${a.zone.padEnd(25)} ${a.level} dB — ${a.msg}`),
    ``,
    `Generated by LibraryQuiet System`,
  ];
  const blob = new Blob([lines.join('\n')],{type:'text/plain'});
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href=url; a.download=`${r.type.replace(/\s+/g,'_')}_${r.date}.txt`; a.click();
  URL.revokeObjectURL(url);
  showToast('⬇ Report downloaded!','success');
}

function showToast(msg,type='info') {
  const t=el('toast'); t.textContent=msg; t.className=`toast ${type} show`;
  clearTimeout(t._t); t._t=setTimeout(()=>t.classList.remove('show'),3000);
}

document.addEventListener('keydown',e=>{ if(e.key==='Escape'){ closeView(); closeGenModal(); } });

document.addEventListener('DOMContentLoaded_SKIP',()=>{
  AppData.applySession();
  startClock();
  renderStats();
  renderReportTypes();
  renderTable();
  AppData.updateNotifBadge();
});

document.addEventListener('DOMContentLoaded', async () => {
  if (window.__LQ_SESSION__) AppData._session = window.__LQ_SESSION__;
  await Promise.all([AppData.loadReports(), AppData.loadAlerts(), AppData.loadZones()]);
  AppData.applySession();
  if (typeof startClock === 'function') startClock();
  if (typeof renderStats === 'function') renderStats();
  if (typeof renderTable === 'function') renderTable();
  if (typeof renderReportTypes === 'function') renderReportTypes();
  AppData.updateNotifBadge();
  setInterval(async () => {
    await AppData.loadReports();
    if (typeof renderStats === 'function') renderStats();
    if (typeof renderTable === 'function') renderTable();
    AppData.updateNotifBadge();
  }, 5000);
});